# Generated by Django 4.0 on 2022-10-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('pincode', models.CharField(default='', max_length=20)),
                ('address', models.EmailField(default='', max_length=100)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.EmailField(max_length=50)),
                ('phone', models.BigIntegerField()),
            ],
        ),
    ]
