# Generated by Django 4.0 on 2022-10-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(default='', max_length=5),
        ),
    ]
