# Generated by Django 4.0 on 2022-10-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_user_phone_alter_user_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='bloodgroup',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirm',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.BigIntegerField(),
        ),
    ]
